Replace `Time.zone.current` with `Time.zone.today` on `Rails::Date` message
The default message for the `strict` style mentions `Time.zone.current`
(e.g. "Do not use `Date.current` without zone. Use `Time.zone.current`
instead.").

Calling `Time.zone.current` causes a `NoMethodError` since there's no `current`
method on `ActiveSupport::TimeZone`. Instead, the message should mention
`Time.zone.today`, which is probably the intended call that takes the time zone
in account.

With this change the message would change to "Do not use `Date.current` without
zone. Use `Time.zone.today` instead."

```ruby
pry(main)> Date.current
Sun, 07 Apr 2019
pry(main)> Time.zone.today
Sun, 07 Apr 2019
pry(main)> Time.zone.current
NoMethodError: undefined method `current' for #<ActiveSupport::TimeZone:0x00007fed55407668>
from (pry):13:in `<main>'
```