Add `require: rubocop-rails` to .rubocop.yml
This commit adds `require: rubocop-rails` to .rubocop.yml
to fix the following error.

```console
% cd path/to/rubocop-rails
% bundle exec rubocop -V
Error: unrecognized cop Rails found in .rubocop.yml
% bundle exec rubocop --show-cops
Error: unrecognized cop Rails found in .rubocop.yml
```

This is because `Rails` department is not included in the
`Registry.global.departments` unless rubocop-rails itself
is required.

This setting makes it valid to set `Enable: false` for
`Rails` department in .rubocop.yml.
https://github.com/rubocop-hq/rubocop-rails/blob/v2.8.1/.rubocop.yml#L25-L26

Related PR ... https://github.com/rubocop-hq/rubocop-rails/pull/75