Revert "Merge pull request #823 from anthony-robin/http-status-routes"
This reverts commit e40d8b9e41daba64364b23df469d534383804951, reversing
changes made to 6051ed83c97e99c008fa9d5c91ed5955d915c804.

The auto-corrected code is not compatible with Rails/Puma, resulting the
error:

    Puma caught this error: undefined method `to_i' for :moved_permanently:Symbol

              status = status.to_i
                             ^^^^^
    Did you mean?  to_s (NoMethodError)
    /.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/request.rb:82:in `handle_request'
    /.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
    /.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'