Fix a build error in the Ruby 3.1 CI matrix
This resolves the following build failure that occurs when using Ruby 3.1 with I18n 1.15.0:

```console
$ bundle exec rake
(snip)

/Users/koic/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/i18n-1.15.0/lib/i18n.rb:58:
in `config': undefined method `[]' for Fiber:Class (NoMethodError)

      current = Fiber[:i18n_config] || self.config = I18n::Config.new
                     ^^^^^^^^^^^^^^
        from /Users/koic/.rbenv/versions/3.1.5/lib/ruby/gems/3.1.0/gems/i18n-1.15.0/lib/i18n.rb:88:in `load_path'
```

https://github.com/rubocop/rubocop-rails/actions/runs/27770437249/job/82263415508

According to the report in https://github.com/ruby-i18n/i18n/issues/735,
this issue has been fixed in I18n 1.15.1 and later. However, the already released I18n 1.15.0
still triggers the build error.

While this could potentially be addressed in a better way on the I18n side,
this change updates the Gemfile to avoid using I18n 1.15.0,
which is known to cause the issue.