Fix an error for `Rails/Delegate`
This PR fixes the following error for `Rails/Delegate` when delegation to a cbase namespaced constant.

```console
  1) RuboCop::Cop::Rails::Delegate detects delegation to a cbase namespaced constant
     Failure/Error: return node.source unless node.namespace

     NoMethodError:
       undefined method 'namespace' for an instance of RuboCop::AST::Node
     # ./lib/rubocop/cop/rails/delegate.rb:113:in 'RuboCop::Cop::Rails::Delegate#full_const_name'
     # ./lib/rubocop/cop/rails/delegate.rb:115:in 'RuboCop::Cop::Rails::Delegate#full_const_name'
     # ./lib/rubocop/cop/rails/delegate.rb:115:in 'RuboCop::Cop::Rails::Delegate#full_const_name'
```

Follow-up to https://github.com/rubocop/rubocop-rails/pull/1438.

There is no changelog entry since this is a bug fix for the above PR that has not been released yet.