[Fix #118] Fix an incorrect autocorrect for `Rails/Validation`
Fixes #118.

This PR fixes an incorrect autocorrect for `Rails/Validation`
when attributes are specified with symbol array literal.

The following auto-corrected causes `NoMethodError`.

```ruby
validates %i[full_name birth_date], presence: true

# => validates_with': undefined method `to_sym' for
#    [:full_name, :birth_date]:Array (NoMethodError)
```

This PR will auto-correct it to the following code.

```ruby
validates :full_name, :birth_date, presence: true
```